# Generated by Django 5.1.7 on 2025-04-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contactmessage_is_read'),
        ('users', '0010_alter_language_name_alter_skill_name'),
    ]

    operations = [
    ]
