# Generated by Django 5.1.6 on 2025-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
