# Generated by Django 5.1.6 on 2025-05-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_interview'),
        ('users', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.interview'),
        ),
    ]
