# Generated by Django 5.1.6 on 2025-06-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_facebook_userprofile_instagram_and_more'),
        ('users', '0015_notification_interview'),
    ]

    operations = [
    ]
