# Generated by Django 5.1.6 on 2025-06-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20250615_1107'),
        ('users', '0016_merge_20250615_1418'),
    ]

    operations = [
    ]
