# Generated by Django 5.1.7 on 2025-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('not_accepted', 'Not Accepted'), ('blocked', 'Blocked')], default='not_accepted', max_length=20)),
            ],
        ),
    ]
