# Generated by Django 5.1.6 on 2025-05-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_admintask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminTask',
        ),
    ]
