# Generated by Django 4.2.19 on 2025-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_after', '0002_event_location_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
