# Generated by Django 4.2.19 on 2025-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf_file',
            new_name='upload',
        ),
    ]
