# Generated by Django 5.1.6 on 2025-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='temp_field',
            field=models.BooleanField(default=False),
        ),
    ]
