# Generated by Django 5.1.6 on 2025-06-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_document_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='temp_field',
        ),
    ]
