# Generated by Django 4.2.20 on 2025-05-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sendreview', '0002_remove_comment_company_remove_comment_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRCompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_request_logos/')),
                ('overview', models.TextField()),
                ('partnership', models.TextField()),
                ('employee_count', models.PositiveIntegerField()),
                ('hr_name', models.CharField(max_length=255)),
                ('hr_email', models.EmailField(max_length=254)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendreview.city')),
            ],
        ),
        migrations.CreateModel(
            name='HRCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='media/company_logos/')),
                ('employee_count', models.PositiveIntegerField()),
                ('overview', models.TextField()),
                ('partnership', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendreview.city')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sendreview.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
