# Generated by Django 5.1.7 on 2025-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
