# Generated by Django 5.1.6 on 2025-05-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='hr_company',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='company.hrcompany'),
            preserve_default=False,
        ),
    ]
