# Generated by Django 4.2.20 on 2025-05-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_joblisting_hr_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='invited_to_interview',
            field=models.BooleanField(default=False),
        ),
    ]
