# Generated by Django 5.1.6 on 2025-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_application_invited_to_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
