# Generated by Django 5.1.7 on 2025-05-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_joblisting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('expired', 'Expired')], default='open', max_length=10),
        ),
    ]
