# Generated by Django 5.1.7 on 2025-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_joblisting_deadline_joblisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
